
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team02-f23-7pm-3
owner: ucsb-cs156-f23
repo_name: team02-f23-7pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjMyMzgwMzU3","is_bot":false,"login":"KateUnger","name":"Kate Unger"},"headRefName":"KateUnger-MenuItemReview-create-controller","number":55,"title":"Create Controller for MenuItemReviews","url":"https://github.com/ucsb-cs156-f23/team02-f23-7pm-3/pull/55"},{"author":{"id":"MDQ6VXNlcjMyMzgwMzU3","is_bot":false,"login":"KateUnger","name":"Kate Unger"},"headRefName":"KateUnger-MenuItemReview-create-db","number":54,"title":"Create DatabaseTable for MenuItemReviews","url":"https://github.com/ucsb-cs156-f23/team02-f23-7pm-3/pull/54"},{"author":{"id":"MDQ6VXNlcjg2NzAzNDk0","is_bot":false,"login":"mucucsb","name":""},"headRefName":"Mu-UCSBOrganizationController-Delete","number":53,"title":"Add DELETE endpoint for a specific record in UCSBOrganization table","url":"https://github.com/ucsb-cs156-f23/team02-f23-7pm-3/pull/53"},{"author":{"id":"MDQ6VXNlcjg2NzAzNDk0","is_bot":false,"login":"mucucsb","name":""},"headRefName":"Mu-UCSBOrganizationController-Put","number":52,"title":"Add PUT (edit) endpoint for a single record in UCSBOrganization table","url":"https://github.com/ucsb-cs156-f23/team02-f23-7pm-3/pull/52"},{"author":{"id":"MDQ6VXNlcjg2NzAzNDk0","is_bot":false,"login":"mucucsb","name":""},"headRefName":"Mu-UCSBOrganizationController-Get","number":51,"title":"Add GET (show) endpoint for a single record in UCSBOrganization table","url":"https://github.com/ucsb-cs156-f23/team02-f23-7pm-3/pull/51"},{"author":{"id":"MDQ6VXNlcjg2NzAzNDk0","is_bot":false,"login":"mucucsb","name":""},"headRefName":"Mu-UCSBOrganizationController-GetandPost","number":50,"title":"Create UCSBOrganizationController, add GET (index) and POST (create)","url":"https://github.com/ucsb-cs156-f23/team02-f23-7pm-3/pull/50"}]
