
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team02-f23-7pm-3
owner: ucsb-cs156-f23
repo_name: team02-f23-7pm-3
pull_requests: [{"author":{"id":"U_kgDOBim1JQ","is_bot":false,"login":"ivan512az","name":"Ivan Hernandez"},"headRefName":"Ivan-HelpRequestDELETE","number":66,"title":"Added DELETE Endpoint for HelpRequest table","url":"https://github.com/ucsb-cs156-f23/team02-f23-7pm-3/pull/66"},{"author":{"id":"U_kgDOBim1JQ","is_bot":false,"login":"ivan512az","name":"Ivan Hernandez"},"headRefName":"Ivan-HelpRequestPUT","number":65,"title":"Added PUT endpoint for a single record in HelpRequest","url":"https://github.com/ucsb-cs156-f23/team02-f23-7pm-3/pull/65"},{"author":{"id":"MDQ6VXNlcjg2NzAzNDk0","is_bot":false,"login":"mucucsb","name":""},"headRefName":"Mu-UCSBOrganization","number":60,"title":"Add GET (show) endpoint for a single record in UCSBOrganization table","url":"https://github.com/ucsb-cs156-f23/team02-f23-7pm-3/pull/60"},{"author":{"id":"MDQ6VXNlcjIyMzU4NDcx","is_bot":false,"login":"ThatsBadJuju","name":""},"headRefName":"Kevin-DiningMenuTable","number":56,"title":"Create UCSBDiningCommonsMenuItemController, add GET (index) and POST (create)","url":"https://github.com/ucsb-cs156-f23/team02-f23-7pm-3/pull/56"}]
