
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team02-f23-7pm-3
owner: ucsb-cs156-f23
repo_name: team02-f23-7pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjg2NzAzNDk0","is_bot":false,"login":"mucucsb","name":""},"headRefName":"Mu-UCSBOrganization-Controller","number":47,"title":"Create UCSBOrganizationController, add GET (index) and POST (create)","url":"https://github.com/ucsb-cs156-f23/team02-f23-7pm-3/pull/47"},{"author":{"id":"U_kgDOCLmKQA","is_bot":false,"login":"rosillo-m","name":"Mariana Rosillo"},"headRefName":"Mariana-ArticlesTable","number":45,"title":"Created Database for Articles","url":"https://github.com/ucsb-cs156-f23/team02-f23-7pm-3/pull/45"},{"author":{"id":"U_kgDOBim1JQ","is_bot":false,"login":"ivan512az","name":"Ivan Hernandez"},"headRefName":"Ivan-HelpRequestTable","number":44,"title":"Created database table for HelpRequest","url":"https://github.com/ucsb-cs156-f23/team02-f23-7pm-3/pull/44"}]
