
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team02-f23-7pm-3
owner: ucsb-cs156-f23
repo_name: team02-f23-7pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjMyMzgwMzU3","is_bot":false,"login":"KateUnger","name":"Kate Unger"},"headRefName":"KateUnger-MenuItemReview-create-put","number":71,"title":"Add Put Request MenuItemReview","url":"https://github.com/ucsb-cs156-f23/team02-f23-7pm-3/pull/71"},{"author":{"id":"MDQ6VXNlcjMyMzgwMzU3","is_bot":false,"login":"KateUnger","name":"Kate Unger"},"headRefName":"KateUnger-MenuItemReview-create-delete","number":70,"title":"Add Delete Request to MenuItemReview","url":"https://github.com/ucsb-cs156-f23/team02-f23-7pm-3/pull/70"},{"author":{"id":"MDQ6VXNlcjIyMzU4NDcx","is_bot":false,"login":"ThatsBadJuju","name":""},"headRefName":"Kevin-DiningMenuTable-Put","number":69,"title":"Added Put (edit) endpoint and tests for UCSBDiningCommonsMenuItems","url":"https://github.com/ucsb-cs156-f23/team02-f23-7pm-3/pull/69"},{"author":{"id":"MDQ6VXNlcjIyMzU4NDcx","is_bot":false,"login":"ThatsBadJuju","name":""},"headRefName":"Kevin-DiningMenuTable-Get","number":68,"title":"Added GET (show) endpoint and tests for a single record in UCSBDiningCommonsMenuItems","url":"https://github.com/ucsb-cs156-f23/team02-f23-7pm-3/pull/68"}]
